export default {};

// pulled from local storage value, generated by blockly
// export default {
//   blocks: {
//     languageVersion: 0,
//     blocks: [
//       {
//         type: 'define_wte',
//         id: 'define_wte_1758730759830',
//         x: 50,
//         y: 38,
//         fields: { NAME: 'bonuses' },
//         inputs: {
//           OUTPUT: {
//             block: {
//               type: 'add',
//               id: '|nGTY/U;q#WvFsNj1n_:',
//               extraState: { length: 2 },
//               inputs: {
//                 value_0: {
//                   block: {
//                     type: 'conditional_number',
//                     id: 'F4m3$~oRYv%g1Jodsu}l',
//                     inputs: {
//                       CONDITION: {
//                         block: {
//                           type: 'logic_compare',
//                           id: '.9Ze5aUl|oOWh1]3n?~{',
//                           fields: { OP: 'GTE' },
//                           inputs: {
//                             A: {
//                               block: {
//                                 type: 'context_variable',
//                                 id: '/[B]6[Gyg*.1rA+UkF-0',
//                                 fields: { VARIABLE_NAME: 'wrvu' },
//                               },
//                             },
//                             B: {
//                               block: {
//                                 type: 'context_variable',
//                                 id: '$2{xTGQA/N0Um!PZnV$`',
//                                 fields: { VARIABLE_NAME: 'wrvu_bonus_threshold' },
//                               },
//                             },
//                           },
//                         },
//                       },
//                       TRUE_VALUE: {
//                         block: {
//                           type: 'math_number',
//                           id: '5mGEzP`V^r,czO}jW6dd',
//                           fields: { NUM: 5 },
//                         },
//                       },
//                       FALSE_VALUE: {
//                         block: {
//                           type: 'math_number',
//                           id: 'GA_5d%%Q.LSu{M8GO]AP',
//                           fields: { NUM: 0 },
//                         },
//                       },
//                     },
//                   },
//                 },
//                 value_1: {
//                   block: {
//                     type: 'conditional_number',
//                     id: 'b7M+e8;-Vh%yVXooSvX7',
//                     inputs: {
//                       CONDITION: {
//                         block: {
//                           type: 'logic_compare',
//                           id: 'tTO+C;A.S:+HCDv6)hIS',
//                           fields: { OP: 'GTE' },
//                           inputs: {
//                             A: {
//                               block: {
//                                 type: 'context_variable',
//                                 id: '{UDuxjHUcA1QiQPUdo1b',
//                                 fields: { VARIABLE_NAME: 'hours' },
//                               },
//                             },
//                             B: {
//                               block: {
//                                 type: 'context_variable',
//                                 id: 'b.)6TGU]$Cj%I2#If+Az',
//                                 fields: { VARIABLE_NAME: 'hour_bonus_threshold' },
//                               },
//                             },
//                           },
//                         },
//                       },
//                       TRUE_VALUE: {
//                         block: {
//                           type: 'math_number',
//                           id: 'N.vWsI66U3b8x$S~PV_E',
//                           fields: { NUM: 1 },
//                         },
//                       },
//                       FALSE_VALUE: {
//                         block: {
//                           type: 'math_number',
//                           id: 'B3I@;NoFu13!qX3Mw;S$',
//                           fields: { NUM: 0 },
//                         },
//                       },
//                     },
//                   },
//                 },
//               },
//             },
//           },
//         },
//       },
//       {
//         type: 'define_wte',
//         id: '(}G3k6}hlGQ$mHcci=dN',
//         x: 52,
//         y: 494,
//         fields: { NAME: 'main' },
//         inputs: {
//           OUTPUT: {
//             block: {
//               type: 'add',
//               id: 'G$hl?=EcBk1C6~*}FvuV',
//               extraState: { length: 3 },
//               inputs: {
//                 value_0: {
//                   block: {
//                     type: 'context_variable',
//                     id: 'T}}Eov#QL@.L{37VE(hJ',
//                     fields: { VARIABLE_NAME: 'base_pay' },
//                   },
//                 },
//                 value_1: {
//                   block: {
//                     type: 'call_wte',
//                     id: 'Qrg0m;T@}FvJ6Lk{9t.N',
//                     extraState: { name: 'bonuses' },
//                     fields: { NAME: 'bonuses' },
//                   },
//                 },
//                 value_2: {
//                   block: {
//                     type: 'call_wte',
//                     id: 'r_QJa#+Jde~yoF=)kUlB',
//                     extraState: { name: 'group_bonus' },
//                     fields: { NAME: 'group_bonus' },
//                   },
//                 },
//               },
//             },
//           },
//         },
//       },
//       {
//         type: 'call_wte',
//         id: '(`67%6wfxH)WNOb;{1JN',
//         x: 44,
//         y: 711,
//         extraState: { name: 'main' },
//         fields: { NAME: 'main' },
//       },
//       {
//         type: 'define_wte',
//         id: ';z+l6z@m83zER2.v,rvr',
//         x: 50,
//         y: 271,
//         fields: { NAME: 'group_bonus' },
//         inputs: {
//           OUTPUT: {
//             block: {
//               type: 'conditional_number',
//               id: '3=a$u[Xvfmv{A|4p%pVR',
//               inputs: {
//                 CONDITION: {
//                   block: {
//                     type: 'logic_compare',
//                     id: 'f[_3#o}QsQYp5~{R55#S',
//                     fields: { OP: 'GTE' },
//                     inputs: {
//                       A: {
//                         block: {
//                           type: 'array_math',
//                           id: '*b~TFZ1_XIStj!6-.Z{c',
//                           fields: { MATH_TYPE: 'AVERAGE' },
//                           inputs: {
//                             LIST: {
//                               block: {
//                                 type: 'segment_frame',
//                                 id: 'pr_tYJJkJDid3n.(V).8',
//                                 fields: { NAME: 'seg1', SEGMENT_ID: '5' },
//                                 inputs: {
//                                   OUTPUT: {
//                                     block: {
//                                       type: 'context_variable',
//                                       id: '!o*b^ot7DuCJn2Q;FGr/',
//                                       fields: { VARIABLE_NAME: 'wrvu' },
//                                     },
//                                   },
//                                 },
//                               },
//                             },
//                           },
//                         },
//                       },
//                       B: {
//                         block: {
//                           type: 'context_variable',
//                           id: 'YNeGTf+pYS^Up_*meffU',
//                           fields: { VARIABLE_NAME: 'wrvu_bonus_threshold' },
//                         },
//                       },
//                     },
//                   },
//                 },
//                 TRUE_VALUE: {
//                   block: { type: 'math_number', id: 'J}L`fB{:[p%C4;sQ-L?B', fields: { NUM: 0.5 } },
//                 },
//                 FALSE_VALUE: {
//                   block: { type: 'math_number', id: 'CE1?Uq)9)69Y7x1E8W}3', fields: { NUM: 0 } },
//                 },
//               },
//             },
//           },
//         },
//       },
//     ],
//   },
// };
