import wtes from '../wtes.js';
const context = {};

// sample jackson comp model - using our js serializer
// TODO: make importable - already copied and using in tests
wtes.define_wte('clinical_base', context => wtes.sum((wtes.multiply((wtes.context_variable(context, 'sc_median_benchmark')), (wtes.context_variable(context, 'cfte')))), (wtes.context_variable(context, 'clinical_external_dollars'))));
wtes.define_wte('clinical_incentive', context => wtes.conditional_number(wtes.context_variable(context, 'prior_year_rvu_total'), 'less_than', wtes.context_variable(context, 'cfte_adjusted_rvu_50'), wtes.number(0), wtes.conditional_number(wtes.sum((wtes.context_variable(context, 'jup_cfte')), (wtes.context_variable(context, 'clinical_external_fte'))), 'less_than', wtes.number(0.5), wtes.multiply((wtes.subtract((wtes.min((wtes.context_variable(context, 'prior_year_rvu_total')), (wtes.context_variable(context, 'cfte_adjusted_rvu_90')))), (wtes.context_variable(context, 'cfte_adjusted_rvu_50')))), (wtes.context_variable(context, 'base_comp_per_wrvu')), wtes.number(0.85)), wtes.multiply((wtes.max((wtes.subtract((wtes.context_variable(context, 'prior_year_rvu_total')), (wtes.context_variable(context, 'cfte_adjusted_rvu_60')))), wtes.number(0))), (wtes.context_variable(context, 'base_comp_per_wrvu')), wtes.number(0.85)))));
wtes.define_wte('academic_base', context => wtes.sum((wtes.context_variable(context, 'external_contract_cfte')), (wtes.context_variable(context, 'gme_admin_dollars')), (wtes.context_variable(context, 'academic_service_time_dollars')), (wtes.context_variable(context, 'dept_other_admin_dollars')), (wtes.context_variable(context, 'other_clinical_admin_dollars')), (wtes.context_variable(context, 'direct_gme')), (wtes.context_variable(context, 'direct_ume')), (wtes.context_variable(context, 'ext_funded_research')), (wtes.context_variable(context, 'internal_research'))));
wtes.define_wte('quality_incentive', context => wtes.multiply((wtes.conditional_number(wtes.context_variable(context, 'prior_year_rvu_total'), 'greater_than', wtes.multiply((wtes.context_variable(context, 'cfte_adjusted_rvu_50')), wtes.number(0.9)), wtes.multiply((wtes.subtract((wtes.context_variable(context, 'sc_60_percentile_benchmark')), (wtes.context_variable(context, 'sc_median_benchmark')))), (wtes.context_variable(context, 'jup_cfte'))), wtes.number(0))), (wtes.context_variable(context, 'payout_cap'))));
wtes.define_wte('total_comp', context => wtes.sum((wtes.call_wte('clinical_base', context)), (wtes.call_wte('academic_base', context)), (wtes.context_variable(context, 'rank_recognition')), (wtes.call_wte('clinical_incentive', context)), (wtes.call_wte('quality_incentive', context))));
wtes.call_wte('total_comp', context);